lk/urls.py
from . import views
from django.urls import path
from django.conf.urls import url

urlpatterns = [
    path('', views.home, name='home'),
    path('<slug:slug>', views.profile, name='profile_detail'),
    path('account/', views.account, name='account'),
    path('account/update/', views.update_params, name='api_update_params'),
    path('diary/posts/', views.get_diary_list, name='api_diary'),
    path('accounts/login/', views.main_redirect_view, name='main_redirect'),
    path('news/', views.news_list, name='news_list'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account import views as auth_views
from django.conf.urls import url
from django.views.generic import TemplateView, RedirectView
from rest_framework_swagger.views import get_swagger_view
from django.conf.urls.static import static
from project import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lk.urls'), name='home'),
    path('', include('voice_bot.urls'), name='bot'),
    path('video/', include('video-processing.urls'), name='videos'),
    path('tasks/', include('tasks.urls'), name='tasks'),
    url(r'^email-verification/$',
        TemplateView.as_view(template_name="email_verification.html"),
        name='email-verification'),
    url(r'^password-reset/$',
        TemplateView.as_view(template_name="password_reset.html"),
        name='password-reset'),
    url(r'^password-reset/confirm/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password-reset-confirm'),

    url(r'^user-details/$',
        TemplateView.as_view(template_name="user_details.html"),
        name='user-details'),
    url(r'^password-change/$',
        TemplateView.as_view(template_name="password_change.html"),
        name='password-change'),

    # this url is used to generate email content
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        TemplateView.as_view(template_name="password_reset_confirm.html"),
        name='password_reset_confirm'),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    url(r'^account/', include('allauth.urls')),
    path('accounts/confirm-email/', auth_views.ConfirmEmailView.as_view(template_name='email_confirm.html'),
         name="account_email_verification_sent"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lk/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

# Create your models here.

GENDER = (
    (0, "MALE"),
    (1, "FEMALE")
)

STATUS = (
    (0, "Врач"),
    (1, "Пациент"),
    (2, "Тестировщик"),
    (3, "Исследователь")
)


class UserProfile(models.Model):
    """
    Extended user model
    """
    # Ссылка на объект пользователя
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Имя
    name = models.CharField(max_length=50, blank=True)
    # Фамилия
    vorname = models.CharField(max_length=50, blank=True)
    # Отчество
    fathername = models.CharField(max_length=50, blank=True)
    gender = models.IntegerField(choices=GENDER, default=0)
    age = models.DateField(default=datetime.date(2000, 1, 1))
    # Статус в проекте — врач, пациент, тестировщик...
    status = models.IntegerField(choices=STATUS, default=0)
    # Опыт
    exp = models.IntegerField(default=0)
    # Флаг, указывающий на заполненные дополнительные поля
    isFull = models.BooleanField(default=False)
    # Город проживания
    city = models.CharField(max_length=50, blank=True)
    # URL на личную страницу
    slug = models.SlugField(null=True)
    # Avatar
    avatar = models.ImageField(upload_to="avatars", default="lk/static/images/toothless.jpg")

    def __str__(self):
        return "%s's profile" % self.user

    def get_absolute_url(self):
        """
        Makes slug
        :return: absolute url with slug
        """
        return reverse('profile_detail', kwargs={'slug': self.slug})


def create_user_profile(sender, instance, created, **kwargs):
    """
    This function will create UserProfile parallel with new User
    :param sender: NOT_USED
    :param instance: User object
    :param created: NOT_USED
    :param kwargs: User args
    :return:
    """
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)
        profile.slug = slugify(profile.user.get_username())
        profile.save()


post_save.connect(create_user_profile, sender=User)


class DiaryRecording(models.Model):
    """
    Diary recording model
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    header = models.CharField(max_length=50, blank=True)
    text = models.CharField(max_length=2000, blank=True)
    published = models.DateTimeField(default=timezone.now)


class NewsRecording(models.Model):
    """
    News recording model
    """
    header = models.CharField(max_length=50, blank=True)
    text = models.CharField(max_length=2000, blank=True)
    published = models.DateTimeField(default=timezone.now)
    img = models.ImageField(upload_to='news')

lk/forms.py
from django import forms
from django.core.files.images import get_image_dimensions
from .models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['name', 'vorname', 'fathername', 'gender', 'age', 'status', 'city', 'avatar']

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']

        try:
            w, h = get_image_dimensions(avatar)

            # validate dimensions
            max_width = max_height = 2000
            if w > max_width or h > max_height:
                raise forms.ValidationError(
                    u'Please use an image that is '
                     '%s x %s pixels or smaller.' % (max_width, max_height))

            # validate content type
            main, sub = avatar.content_type.split('/')
            if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif', 'png']):
                raise forms.ValidationError(u'Please use a JPEG, '
                    'GIF or PNG image.')

            # validate file size
            # if len(avatar) > (20 * 1024):
            #     raise forms.ValidationError(
            #         u'Avatar file size may not exceed 20k.')

        except AttributeError:
            """
            Handles case when we are updating the user profile
            and do not supply a new avatar
            """
            pass
        return avatar

lk/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from rest_framework.decorators import api_view
from rest_framework.response import Response
from voice_bot.decorators import add_bot
from .forms import UserProfileForm
from .models import UserProfile, DiaryRecording, NewsRecording
from .serializers import DiaryRecordingSerializer, NewsRecordingSerializer, UserProfileSerializer


def profile(request, slug):
    """
    This function return user profile that contains slug
    :param request:
    :param slug: slug to UProfile
    :return: render
    """
    u_profile = get_object_or_404(UserProfile, slug=slug)
    return render(request, 'friends.html', {'profile': u_profile})


@login_required()
def account(request):
    """
    way to account with ability to change user fields
    :param request:
    :return:
    """
    u_profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            u_profile.name = form.cleaned_data['name']
            u_profile.vorname = form.cleaned_data['vorname']
            u_profile.fathername = form.cleaned_data['fathername']
            u_profile.gender = form.cleaned_data['gender']
            u_profile.age = form.cleaned_data['age']
            u_profile.status = form.cleaned_data['status']
            u_profile.city = form.cleaned_data['city']
            u_profile.avatar = form.cleaned_data['avatar']
            u_profile.isFull = True
            u_profile.save()
            return HttpResponseRedirect('/account/')

    else:
        init_data = UserProfileSerializer(u_profile).data
        init_data['avatar'] = u_profile.avatar
        form = UserProfileForm(initial=init_data)
    return render(request, 'account.html', {'profile': u_profile,
                                            'form': form})


@login_required()
@api_view(['POST'])
def update_params(request):
    """
    Used to update Users parameters, such as name, vorname and others
    :param request:
    :return:
    """
    if request.method == 'POST':
        u_profile = get_object_or_404(UserProfile, user=request.user)
        if 'name' in request.data:
            u_profile.name = str(request.data['name'])
        if 'vorname' in request.data:
            u_profile.vorname = str(request.data['vorname'])
        if 'fathername' in request.data:
            u_profile.fathername = str(request.data['fathername'])
        if 'status' in request.data:
            try:
                u_profile.status = int(request.data['status'])
            except ValueError:
                return Response({"message": "status should be INT!"})
        if 'city' in request.data:
            u_profile.city = str(request.data['city'])
        u_profile.save()
        return Response({"message": "Successfully updated!"})
    return Response({"message": "Method not allowed!"})


def news_list(request):
    """
    page with news list
    :param request:
    :return:
    """
    return render(request, 'news.html', {"recordings": NewsRecordingSerializer(NewsRecording.objects.all(),
                                                                               many=True).data})


@login_required()
@api_view(['GET', 'POST'])
def get_diary_list(request):
    """
    Creates new diary recording or returns all recording list
    :param request:
    :return:
    """
    if request.method == 'GET':
        return Response({"recordings": DiaryRecordingSerializer(DiaryRecording.objects.filter(user=request.user),
                                                                many=True).data})
    elif request.method == 'POST':
        serializer = DiaryRecordingSerializer(data=request.data)
        try:
            DiaryRecording.objects.create(user=request.user, header=request.data['header'],
                                          text=request.data['text'])
            return Response({"message": "Recording created!"})
        except KeyError:
            return Response({"message": "Error!"})
    else:
        return Response({"message": "Method not allowed!"})


def main_redirect_view(request):
    """
    redirects to main page
    :param request:
    :return:
    """
    return HttpResponseRedirect('/')


@add_bot(bot_name='bot')
def home(request, **kwargs):
    """
    This funciton represents the main page
    :param request:
    :return:
    """
    if not request.user.is_anonymous:
        u_profile = get_object_or_404(UserProfile, user=request.user)
    else:
        u_profile = {'name': "Имя", 'vorname': "Фамилия"}
    return render(request, 'main.html', {"recordings": NewsRecordingSerializer(NewsRecording.objects.all(),
                                                                               many=True).data,
                                         'profile': u_profile,
                                         "commands": kwargs['commands'],
                                         "bot_name": kwargs['bot_name']})

lk/templates/account.html
{% extends 'frontend-common/page-with-2-sections.html' %}

{% load static %}

{% block local-style %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block local-script %}
    <script>
		document.addEventListener('DOMContentLoaded', e => {
			let tabElements = document.querySelectorAll('.tabs')
			let result = M.Tabs.init(tabElements, {})

			let datepickers = document.querySelectorAll('.datepicker')
			result = M.Datepicker.init(datepickers, {
				format: 'yyyy-mm-dd'
			})
		})
	</script>

	<script>
		$(document).ready(function(){
    		$('select').formSelect();
  		});
  	</script>
{% endblock %}

{% block content %}
    {{ block.super }}

    <div id="content-main">
        <div id="profile-summary">
            <div id="profile-summary-head-spacer"></div>
            <div id="profile-avatar-wrapper"></div>
            <img id="profile-avatar" src="{{ profile.avatar.url }}" alt="">
            <div id="profile-summary-head-spacer-2"></div>
            <div id="profile-summary-content">
                <div id="profile-name">
                    {{ profile.name }} {{ profile.vorname }}
                </div>
                {% comment %} <div id="profile-description">
                    {% if profile.status == 0 %}
                        Врач
                    {% elif profile.status == 1%}
                        Пациент
                    {% elif profile.status == 2%}
                        Тестировщик
                    {% elif profile.status == 3%}
                        Исследователь
                    {% endif %}
                </div> {% endcomment %}



                {% comment %} <div id="profile-short-stats">
                    <div class="stat-entry">
                        <div class="number">32</div>
                        <div class="text">Друга</div>
                    </div>
                    <div class="stat-entry">
                        <div class="number">8</div>
                        <div class="text">Видео</div>
                    </div>
                    <div class="stat-entry">
                        <div class="number">105</div>
                        <div class="text">Записей</div>
                    </div>
                </div> {% endcomment %}
                {% comment %} <div id="profile-status">
                    Откладывать на завтра то, что можно сделать сегодня, — мое хобби. С утра до ночи откладывала бы
                    не щадя живота.
                </div> {% endcomment %}
                <div id="profile-actions">

                </div>
            </div>
        </div>

        <div id="profile-non-summary">
            <h4>Общая информация</h4>

            <div id="profile-general" style="margin: 0em 2.5em;">
                {% comment %} <div class="row valign-wrapper">
                    <div class="col s12">
                        <div class="row">
                            <form action="/account/" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form }}
                                <input type="submit" value="Submit">
                            </form>
                        </div>
                    </div>
                </div> {% endcomment %}
                <div class="row">
                    <div class="col s4">
                        <div class="col-content">
                            <label for="last-name">Фамилия</label>

                            {{ form.vorname }}
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="col-content" id="first-name">
                            <label for="first-name">Имя</label>

                            {{ form.name }}
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="col-content" id="second-name">
                            <label for="second-name">Отчество</label>

                            {{ form.fathername }}
                        </div>
                    </div>

                    <div class="col s4">
                        <div class="col-content" id="birth-date">
                            <label for="birth-date">Дата рождения</label>

                            {{ form.age }}
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="col-content" id="city">
                            <label for="city">Город</label>

                            {{ form.city }}
                            {% comment %} <select>
                                <option value="" disabled selected>Выберете город</option>
                                <option value="1">Санкт-Петербург</option>
                                <option value="2">Москва</option>
                                <option value="3">Новосибирск</option>
                                <option value="4">Владивосток</option>
                            </select> {% endcomment %}
                        </div>
                    </div>

                    <div class="col s4">
                        <div class="col-content" id="sex">
                            <label for="sex">Пол</label>
                            {{ form.gender }}
                            {% comment %} <select>
                                <option value="" disabled selected>Выберете пол</option>
                                <option value="1">Мужской</option>
                                <option value="2">Женский</option>
                            </select> {% endcomment %}
                        </div>
                    </div>

                    {% comment %} <div class="col s4">
                        <div class="col-content" id="role" style="height: 79.5px !important;"> <!-- This is needed because of the use of {{ form.status }}. TODO: FIX -->
                            <label for="role">Роль</label>
                            <!-- <input type="text" id="role" placeholder="Роль"> -->
                            {{ form.status }}
                        </div>
                    </div> {% endcomment %}

                    {% comment %} <div class="col s8 longer-one">
                        <div class="text">
                            Если Вы яляетесь врачом или пациентом необходимо подтвердить это, введя специальный код в поле:
                        </div>
                        <div class="col-content" id="code">
                            <label for="code">Код</label>
                            <input type="text" id="code">
                        </div>
                    </div> {% endcomment %}
                </div>
            </div>

            {% comment %} <h4>Статистика</h4>

            <div id="profile-statistics">
                <img src="{% static 'images/oval.svg' %}" alt="">
                <p class="flow-text">После того, как Вы выполните задания, здесь появится Ваша статистика :)</p>
            </div> {% endcomment %}
        </div>
    </div>
{% endblock %}

lk/templates/base.html
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="one-more-city">

    <title>Заходи, не стесняйся</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- <link rel="stylesheet" href="{% static 'css/materialize/materialize.css' %}" /> -->
    
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/only-size.css' %}  ?ver=2" /> -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/main-for-all-page.css' %}  ?ver=2" /> -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> -->
    <script src="{% static 'js/materialize.min.js' %}"></script>

    {% load i18n %}
    {% load account socialaccount %}
  </head>

<body>
  <!--  -->

  
  <!--  -->
  <!-- или реально присралось или скучно -->

  </body>
</html>

lk/templates/email_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Подтверждение e-mail</title>

    {% load i18n %}
    {% load account %}


</head>
<body>
    <div class="screen-height-filler valign-wrapper container demo-1 full-screen">
        <div id="large-header" class="large-header outer">
            <canvas id="demo-canvas"></canvas>
            <div class="container row center inner" style="top: 50%;">
                <div class="col m8 offset-m2 s12 white popup">
                    <h2>{% trans "Confirm E-mail Address" %}</h2>
                    <div class="divider"></div>

                    {% user_display confirmation.email_address.user as user_display %}
                    <div class="section center">
                        <p class="text_for_user">Пожалуйста, подтвердите, что данный e-mail <a href="mailto:{{ email }}">{{ email }}</a> принадлежит пользователю {{ user_display }}.</p>
                        <form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
                            {% csrf_token %}
                            <button
                            class="btn-large waves-effect waves-light"
                            type="submit">{% trans 'Confirm' %}</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>


</body>
</html>

lk/templates/email_verification.html
{% extends "page.html" %}

{% load static %}

{% block body %}
  <div class="row">
    <h3>E-mail verification</h3><hr/>
    {% include "fragments/email_verification_form.html" %}
  </div>
{% endblock %}

lk/templates/friends.html
{% extends 'frontend-common/page-with-2-sections.html' %}

{% load static %}

{% block local-style %}
    <link rel="stylesheet" href="{% static 'css/friends.css' %}">
{% endblock %}

{% block local-script %}
	<script>
		document.addEventListener('DOMContentLoaded', e => {
			let tabElements = document.querySelectorAll('.tabs')
			let result = M.Tabs.init(tabElements, {})

			let datepickers = document.querySelectorAll('.datepicker')
			result = M.Datepicker.init(datepickers, {
				format: 'yyyy-mm-dd'
			})
		})
	</script>

	<script>
		$(document).ready(function(){
    		$('select').formSelect();
  		});
  	</script>
{% endblock %}

{% block content %}
    {{ block.super }}

    <div class="container" style="width:100%; max-width: 100%; margin: 0%">
		<div class="row">
			<div class="col s12 m4 l4 first-column">
				<div class="row valign-wrapper center">
					<div class="col s12">
						<h5>ЛичaDWadый кабинет</h5>
					</div>
				</div>
				<div class="row valign-wrapper center">
					<div class="col s12" >
					  <img src="{% static 'images/toothless.jpg' %}" alt="Profile Photo" class="circle responsive-img" >
					</div>
				</div>
				<div class="row valign-wrapper center">
					<div class="col s12">
					  <p>Имя Фамилия</p>
					</div>
				</div>
				<div class="row valign-wrapper center">
					<div class="col s12">
					  <p>Статус (врач)</p>
					</div>
				</div>
			</div>

			<div class="col s12 m8 l8 second-column">
				<div class="row valign-wrapper">
					<div class="col s12">
						<h5>Подробная информация</h5>
					</div>
				</div>
				<div class="row valign-wrapper">
					<div class="col s12">
						<div class="row">
							<form class="col s12">
							  <div class="row">
								<div class="input-field col s12 m4 l4">
									<input value="{{name}}" id="surname" type="text" class="validate" tabindex="1">
									<label for="surname">Фамилия</label>
								</div>
								<div class="input-field col s12 m4 l4">
								  <input value="{{vorname}}" id="name" type="text" class="validate" tabindex="2">
								  <label for="name">Имя</label>
								</div>
								<div class="input-field col s12 m4 l4">
									<input value="{{fname}}" id="patronym" type="text" class="validate" tabindex="3">
									<label for="patronym">Отчество</label>
								</div>

								<div class="input-field col s6 m4">
									<input id="id_age" name="age" tabindex="4" type="text" class="col datepicker" placeholder="Дата рождения">
									<label for="id_age">Дата рождения:</label>
								</div>

								<div class="input-field col s6 m4">
									<input id="id_city" name="city" tabindex="5" type="text"class="validate" placeholder="Город проживания">
									<label for="id_city">Город проживания:</label>
								</div>

								<div class="col s12 m4">
									<label for="id_gender">Пол:</label>
									<p>
									<label>
										<input value="0" type="radio" name="gender" id="id_gender" tabindex="5" checked/>
										<span>Мужской</span>
									</label>
									</p>
									<p>
									<label>
										<input name="gender" value="1" tabindex="6"  id="id_gender" type="radio" />
										<span>Женский</span>
									</label>
									</p>
								</div>
								<!-- <div class="input-field col s6 m6">
									<input id="email_inline" type="email" class="validate">
									<label for="email_inline">Email</label>
									<span class="helper-text" data-error="wrong" data-success="right">Helper text</span>
								</div> -->

								<div class="input-field col s12 m6">
									<select>
									  <option value="" disabled selected>Роль в проекте</option>
									  <option value="1">Пациент</option>
									  <option value="2">Родственник</option>
									  <option value="3">Врач</option>
									  <option value="4">Тестировщик</option>
									  <option value="3">Исследователь</option>
									</select>
									<label>Роль в проекте</label>
								</div>

								<div class="input-field col s12">
									<span>Далее необходимо указать Вашу роль в данном проекте. Если Вы являетесь пациентом, родственником или врачом, то Вам необходимо подтвердить вашу роль. Для этого внесите в следующее поле персональный код, выданный администратором.</span>
								</div>



								<!-- <div class="input-field col s6">
								  <input id="last_name" type="text" class="validate">
								  <label for="last_name">Last Name</label>
								</div> -->
							  </div>

							  <div class="row">
								<div class="input-field col s12">
								  <input id="password" type="password" class="validate">
								  <label for="password">Password</label>
								</div>
							  </div>
							  <div class="row">
								<div class="input-field col s12">
								  <input id="email" type="email" class="validate">
								  <label for="email">Email</label>
								</div>
							  </div>
							  <div class="row">
								<div class="col s12">
								  This is an inline input field:
								  <div class="input-field inline">
									<input id="email_inline" type="email" class="validate">
									<label for="email_inline">Email</label>
									<span class="helper-text" data-error="wrong" data-success="right">Helper text</span>
								  </div>
								</div>
							  </div>
							</form>
						  </div>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% comment %} <div class="section " id="user-profile">
		<div class="card-panel hoverable">
			<div class="row marg">
				<div class="col s12 m7">
					<div class="display-flex media ">
						<div class="col s12 m3">
							<img src="{{avatar}}" alt="users view avatar"
								height="80px" width="80px">
						</div>
						<div class="col s12 m9">
							<div class="media-body">
								<h6 class="media-heading">
									<span class="users-view-name">{{name}}</span>
									<span class="grey-text">@</span>
									<span class="users-view-username grey-text">{{user.username}}</span>
									<blockquote  >
										По всем вопросам пишите в личные сообщения :)
									</blockquote>
								</h6>
							</div>
						</div>
					</div>
				</div>
				<div class="col s12 m5 quick-action-btns display-flex justify-content-end align-items-center pt-2">
					<a href="app-email.html" class="btn-large btn-light-indigo right-align waves-light waves-effect"><i class="material-icons">mail_outline</i></a>
					{% if not isFull %}
					<a href="/accounts/changeform" class="btn-large indigo">Обновить данные</a>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="card ">
			<div class="card-content hoverable">
				<div class="row indigo lighten-5 border-radius-4 mb-2">
					<div class="col s12 m12 users-view-timeline">
						<h6 class="indigo-text m-0">ФИО: <span>{{vorname}} {{name}} {{fname}}</span></h6>
					</div>
				</div>
				<div class="row">
					<div class="col s12">
						<table class="striped">
							<tbody></tbody>
						</table>
						<h6 class="mb-2 mt-2"><i class="material-icons">error_outline</i> Personal Info</h6>
						<table class="striped">
							<tbody>
								<tr>
									<td>Должность:</td>
									<td>{{position}}</td>
								</tr>
								<tr>
									<td>E-mail:</td>
									<td class="users-view-email">{{ email }}</td>
								</tr>
								<tr>
									<td>Стаж</td>
									<td class="users-view-name">{{exp}}</td>
								</tr>
								<tr>
									<td>Username:</td>
									<td class="users-view-username">{{user.username}}</td>
								</tr>
								<tr>
									<td>День рождения:</td>
									<td>{{bdate}}</td>
								</tr>
								<tr>
									<td>Возраст</td>
									<td class="users-view-age">{{age}}</td>
								</tr>
							</tbody>
						</table>
						<h6 class="mb-2 mt-2"><i class="material-icons">link</i> Social Links</h6>
						<table class="striped">
							<tbody>
								<tr>
									<td>Facebook:</td>
									<td><a href="#">https://www.facebook.com/</a></td>
								</tr>
								<tr>
									<td>Instagram:</td>
									<td><a href="#">https://www.instagram.com/</a></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="hat white-text row" style="margin-bottom: 0em;">
		<div class="container m3 s12 center" style="padding: 1em;">
			<h6>© 2020 NTI THEORMECH_RELEASE</h6>
		</div>
	</div> {% endcomment %}
{% endblock %}

lk/templates/password_change.html
{% extends "page.html" %}

{% load static %}

{% block body %}

  <div class="row">
    <div class="form-group">
      <label for="token" class="col-sm-2 control-label">User Token</label>
      <div class="col-sm-4">
        <input name="token" type="text" class="form-control" id="token" placeholder="Token">
        <p class="help-block">Token received after login</p>
      </div>
    </div>
  </div>

  <div class="row">
    <h3>Update User Details</h3><hr/>
    {% include "fragments/password_change_form.html" %}
  </div>
{% endblock %}

{% block local-script %}
    <script type="text/javascript">
      $().ready(function(){
        $('form button[type=submit]').click(function(){
          var token = $('input[name=token]').val();
          var form = $('form');
          $.ajax({
            url: form.attr('action'),
            data: $('form').serialize(),
            type: "POST",
            beforeSend: function(xhr){xhr.setRequestHeader('Authorization', 'Token '+token);}
          }).fail(function(data){error_response(data);})
          .done(function(data){susccess_response(data);});
          return false;
        });

      });
    </script>
{% endblock %}